version: '3.1'

services:

  db:
    image: mysql:5.5
    restart: always
    network_mode: "host"
    ports:
      - "3306:3306"
    volumes:
      - ~/.docker_data/mysql/mysql:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
