version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    network_mode: "host"
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: DcjeGv7dEnQM94EDTs
